/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package TokoBunga;

import java.io.*;
import java.util.logging.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Huawei
 */
public class DeleteDialog extends java.awt.Dialog {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/DB_PBO_P4";
    String user = "postgres";
    String password = "1234";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    public DeleteDialog(java.awt.Frame parent, boolean modal, String id, String nama, String kategori,
            String deskripsi, String harga, String stok, String ukuran) {
        super(parent, modal);
        initComponents();

        TxtIdBunga.setText(id);
        TxtNamaBunga.setText(nama);
        TxtKategoriBunga.setText(kategori);
        TxtDeskripsiProduk.setText(deskripsi);
        TxtHarga.setText(harga);
        TxtStokBunga.setText(stok);
        TxtUkuranBuket.setText(ukuran);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TxtKategoriBunga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDeskripsiProduk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtStokBunga = new javax.swing.JTextField();
        TxtIdBunga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUkuranBuket = new javax.swing.JTextField();
        TxtNamaBunga = new javax.swing.JTextField();
        BtnYa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnTidak = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Kategori Bunga");
        jLabel4.setAutoscrolls(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 105, -1, -1));

        TxtKategoriBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKategoriBungaActionPerformed(evt);
            }
        });
        add(TxtKategoriBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 105, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Deskripsi Produk");
        jLabel5.setAutoscrolls(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 145, -1, -1));

        TxtDeskripsiProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDeskripsiProdukActionPerformed(evt);
            }
        });
        add(TxtDeskripsiProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 135, 110, 40));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Harga");
        jLabel6.setAutoscrolls(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 185, 63, -1));

        TxtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaActionPerformed(evt);
            }
        });
        add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 185, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText(" Stok Bunga");
        jLabel7.setAutoscrolls(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 215, 90, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID Bunga");
        jLabel2.setAutoscrolls(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 45, 87, -1));

        TxtStokBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStokBungaActionPerformed(evt);
            }
        });
        add(TxtStokBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 215, 110, -1));

        TxtIdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBungaActionPerformed(evt);
            }
        });
        add(TxtIdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 45, 110, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Ukuran Buket");
        jLabel8.setAutoscrolls(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 245, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Nama Bunga");
        jLabel3.setAutoscrolls(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 75, -1, -1));

        TxtUkuranBuket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUkuranBuketActionPerformed(evt);
            }
        });
        add(TxtUkuranBuket, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 245, 110, -1));

        TxtNamaBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaBungaActionPerformed(evt);
            }
        });
        add(TxtNamaBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 75, 110, -1));

        BtnYa.setBackground(new java.awt.Color(255, 102, 204));
        BtnYa.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnYa.setForeground(new java.awt.Color(255, 255, 255));
        BtnYa.setText("Ya");
        BtnYa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYaActionPerformed(evt);
            }
        });
        add(BtnYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 30));

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnTidak.setBackground(new java.awt.Color(255, 102, 204));
        BtnTidak.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnTidak.setForeground(new java.awt.Color(255, 255, 255));
        BtnTidak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnTidak.setLabel("Tidak");
        BtnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTidakActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TxtKategoriBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKategoriBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKategoriBungaActionPerformed

    private void TxtDeskripsiProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDeskripsiProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDeskripsiProdukActionPerformed

    private void TxtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaActionPerformed

    private void TxtStokBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStokBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStokBungaActionPerformed

    private void TxtIdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBungaActionPerformed

    private void TxtUkuranBuketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUkuranBuketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUkuranBuketActionPerformed

    private void TxtNamaBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaBungaActionPerformed

    private void BtnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTidakActionPerformed
        dispose();
    }//GEN-LAST:event_BtnTidakActionPerformed

    private void BtnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYaActionPerformed
        String IdBunga;
        if (TxtIdBunga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Id Bunga tidak boleh kosong "
                + "untuk menghapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        IdBunga = TxtIdBunga.getText();


        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            String deleteSql = "DELETE FROM tokobunga WHERE idbunga= ?";
            pstmt = conn.prepareStatement(deleteSql);
            pstmt.setString(1, IdBunga);
            pstmt.executeUpdate();
            pstmt.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            dispose(); // Tutup dialog setelah berhasil
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus "
                 + "data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DeleteDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnYaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DeleteDialog dialog = new DeleteDialog(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTidak;
    private javax.swing.JButton BtnYa;
    private javax.swing.JTextField TxtDeskripsiProduk;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtIdBunga;
    private javax.swing.JTextField TxtKategoriBunga;
    private javax.swing.JTextField TxtNamaBunga;
    private javax.swing.JTextField TxtStokBunga;
    private javax.swing.JTextField TxtUkuranBuket;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
