/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package TokoBunga;

import java.io.*;
import java.util.logging.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Huawei
 */

public class UpdateDialog extends java.awt.Dialog {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/DB_PBO_P4";
    String user = "postgres";
    String password = "1234";

    String idBungaLama, namaBungaLama, kategoriBungaLama, deskripsiLama, hargaLama, stokLama, ukuranLama;

    public void connect() {
        try {
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public UpdateDialog(java.awt.Frame parent, boolean modal, String idBungaLama, String namaBungaLama, String kategoriBungaLama,
            String deskripsiLama, String hargaLama, String stokLama, String ukuranLama) {
        super(parent, modal);
        initComponents();
        connect();

        this.idBungaLama = idBungaLama;
        this.namaBungaLama = namaBungaLama;
        this.kategoriBungaLama = kategoriBungaLama;
        this.deskripsiLama = deskripsiLama;
        this.hargaLama = hargaLama;
        this.stokLama = stokLama;
        this.ukuranLama = ukuranLama;

        TxtIdBunga.setText(idBungaLama);
        TxtNamaBunga.setText(namaBungaLama);
        TxtKategoriBunga.setText(kategoriBungaLama);
        TxtDeskripsiProduk.setText(deskripsiLama);
        TxtHarga.setText(hargaLama);
        TxtStokBunga.setText(stokLama);
        TxtUkuranBuket.setText(ukuranLama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TxtIdBunga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtNamaBunga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtKategoriBunga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDeskripsiProduk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtStokBunga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtUkuranBuket = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BtnUpdate = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID Bunga");
        jLabel2.setAutoscrolls(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 87, -1));

        TxtIdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBungaActionPerformed(evt);
            }
        });
        add(TxtIdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 46, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Nama Bunga");
        jLabel3.setAutoscrolls(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, -1));

        TxtNamaBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaBungaActionPerformed(evt);
            }
        });
        add(TxtNamaBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 76, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Kategori Bunga");
        jLabel4.setAutoscrolls(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));

        TxtKategoriBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKategoriBungaActionPerformed(evt);
            }
        });
        add(TxtKategoriBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 106, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Deskripsi Produk");
        jLabel5.setAutoscrolls(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 146, -1, -1));

        TxtDeskripsiProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDeskripsiProdukActionPerformed(evt);
            }
        });
        add(TxtDeskripsiProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 136, 110, 40));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Harga");
        jLabel6.setAutoscrolls(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 186, 63, -1));

        TxtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaActionPerformed(evt);
            }
        });
        add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 186, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText(" Stok Bunga");
        jLabel7.setAutoscrolls(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 90, -1));

        TxtStokBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStokBungaActionPerformed(evt);
            }
        });
        add(TxtStokBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 216, 110, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Ukuran Buket");
        jLabel8.setAutoscrolls(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, -1, -1));

        TxtUkuranBuket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUkuranBuketActionPerformed(evt);
            }
        });
        add(TxtUkuranBuket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 246, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnUpdate.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpdate.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void TxtIdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBungaActionPerformed

    private void TxtNamaBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaBungaActionPerformed

    private void TxtKategoriBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKategoriBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKategoriBungaActionPerformed

    private void TxtDeskripsiProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDeskripsiProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDeskripsiProdukActionPerformed

    private void TxtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaActionPerformed

    private void TxtStokBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStokBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStokBungaActionPerformed

    private void TxtUkuranBuketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUkuranBuketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUkuranBuketActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed

        if (TxtIdBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtNamaBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtKategoriBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtDeskripsiProduk.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtStokBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtUkuranBuket.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else {
            try {

                String sql = "UPDATE tokobunga SET idbunga= ?, namabunga= ?, kategoribunga= ?, deskripsiproduk= ?, harga= ?, stok= ?, ukuran= ? "
                        + "WHERE idbunga= ? AND namabunga= ? AND kategoribunga= ? AND deskripsiproduk= ? AND harga= ? AND stok= ? AND ukuran= ?";
                pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, TxtIdBunga.getText());
                pstmt.setString(2, TxtNamaBunga.getText());
                pstmt.setString(3, TxtKategoriBunga.getText());
                pstmt.setString(4, TxtDeskripsiProduk.getText());
                pstmt.setInt(5, Integer.parseInt(TxtHarga.getText()));
                pstmt.setInt(6, Integer.parseInt(TxtStokBunga.getText()));
                pstmt.setString(7, TxtUkuranBuket.getText());
                pstmt.setString(8, idBungaLama);
                pstmt.setString(9, namaBungaLama);
                pstmt.setString(10, kategoriBungaLama);
                pstmt.setString(11, deskripsiLama);
                pstmt.setInt(12, Integer.parseInt(hargaLama));
                pstmt.setInt(13, Integer.parseInt(stokLama));
                pstmt.setString(14, ukuranLama);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                    pstmt.close();
                    conn.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                }
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UpdateDialog dialog = new UpdateDialog(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField TxtDeskripsiProduk;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtIdBunga;
    private javax.swing.JTextField TxtKategoriBunga;
    private javax.swing.JTextField TxtNamaBunga;
    private javax.swing.JTextField TxtStokBunga;
    private javax.swing.JTextField TxtUkuranBuket;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
